export interface Training {
  id: number;
  course: string;
  audience: string;
  format: string;
  location: string;
  duration: string;
  specialInstructions: string;
  description: string;
  CEUsAvailable: string;
  prerequisites: string[];
  CTDSHours: string;
  image: string;
}

export const trainingData: Training[] = [
   {
    id: 1,
    course: "Transformational Collaborative Outcomes Management (TCOM) Orientation",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3.5 hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This is the first of two trainings required for MichiCANS certification.",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "3.5 Hours",
    image: "/training-michicans-tcom-orientation.webp",
  },
  {
    id: 2,
    course: "MichiCANS Overview",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3.5 Hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This is the second of two trainings required for MichiCANS certification.",
    CEUsAvailable: "N/A",
    prerequisites: ["Transformational Collaborative Outcomes Management(TCOM) Orientation(MichiCANS)"],
    CTDSHours: "3.5 Hours",
    image: "/training-michicans-action-planning.webp",
  },
  {
    id: 3,
    course: "MichiCANS Annual Certification Booster Training",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "To retain certification in the MichiCANS, staff must pass an annual recertification assessment. There are no training requirements prior to taking the annual recertification. This optional Booster training is offered to those individuals who (1) are already trained in the MichiCANS and (2) are interested in more opportunity for practice and application of the MichiCANS to prepare for recertification.The training will include use of vignettes and practice opportunities to support participants in achieving greater confidence in the use of the MichiCANS tools. Booster training objectives include: • Increase understanding of the certification and recertification process  • Increase accuracy and efficiency in the use of the MichiCANS reference guides and rating sheets • Enhance ability to communicate the youth / family’s story(needs / strengths)   • Increase confidence in the six Communimetric Principles",
    CEUsAvailable: "N/A",
    prerequisites: ["Transformational Collaborative Outcomes Management (TCOM) Orientation (MichiCANS)", "MichiCANS Overview", "MichiCANS Certification", "MichiCANS Action Planning"],
    CTDSHours: "3 Hours",
    image: "/training-michicans-annual-recertification-booster.webp",
  },
  {
    id: 4,
    course: "MichiCANS Action Planning",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This training is required for clinical staff and clinical supervisors after successful completion of MichiCANS Certification (TCOM Orientation, MichiCANS Overview, and successful completion of the vignette-based assessment).",
    CEUsAvailable: "N/A",
    prerequisites: ["Transformational Collaborative Outcomes Management (TCOM) Orientation (MichiCANS)", "MichiCANS Overview"],
    CTDSHours: "3 Hours",
    image: "/training-michicans-action-planning.webp",
  },
  {
    id: 5,
    course: "MichiCANS Supervisory Training",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This training is required for supervisors who oversee staff who will be completing the MichiCANS. This training is taken after successful completion of MichiCANS Certification (TCOM Orientation, MichiCANS Overview, and successful completion of the vignette-based assessment) and Action Planning.",
    CEUsAvailable: "N/A",
    prerequisites: ["Transformational Collaborative Outcomes Management (TCOM) Orientation (MichiCANS)", "MichiCANS Overview", "MichiCANS Certification", "MichiCANS Action Planning"],
    CTDSHours: "3 Hours",
    image: "/training-michicans-supervisory-training.webp",
  },
  {
    id: 6,
    course: "MichiCANS Supervisor Community of Practice Meetings",
    audience: "MichiCANS",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "90 mins",
    specialInstructions: "You must register to gain access. Community of Practice meetings are interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "MichiCANS Supervisor Community of Practice meetings are offered twice per month. These meetings are for clinical supervisors and provide the opportunity to come together in a learning community with a focus on building practical skills to support meaningful use of the MichiCANS across the state and at the organizational level. The primary audience for this offering is clinical supervisors who directly oversee the clinical use of the MichiCANS.",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "N/A",
    image: "/training-michicans-comm-of-practice.webp",
  },
  {
    id: 7,
    course: "Assessment & Management of ASD in Transitional Age Youth and Adults",
    audience: "Autism Spectrum Disorder (ASD)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access.",
    description: "This webinar will provide an overview of the best practice methods and tools for assessing and managing autism for transitional-aged youth and adults, including:• Discussing common comorbidities • Reviewing diagnostic and management challenges • Presenting methods for guiding individuals and families through the transition to adulthood.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 3 hours",
    prerequisites: [],
    CTDSHours: "3 Hours",
    image: "/training-asd-transitional-age-youth.webp",
  },
  {
    id: 8,
    course: "Disentangling Childhood Trauma and ASD: Differential & Comorbid Presentations",
    audience: "Autism Spectrum Disorder (ASD)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access.",
    description: "This webinar will cover useful evaluation components and tools in the assessment of ASD and childhood trauma. The presentation will include differences and commonalities in symptom presentation between ASD and trauma.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 3 hours",
    prerequisites: [],
    CTDSHours: "3 Hours",
    image: "/training-asd-trauma.webp",
  },
  {
    id: 9,
    course: "Understanding Neurodiversity & Conducting Neuroaffirming Evaluations",
    audience: "Autism Spectrum Disorder (ASD)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access.",
    description: "This webinar will cover important topics in neurodiversity relevant to comprehensive autism evaluations across the lifespan, including: • Discussing methods for making the evaluation process comfortable and empowering. • Reviewing case examples for writing helpful reports and recommendations using affirming language that focuses on differences rather than deficits.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 3 hours",
    prerequisites: [],
    CTDSHours: "3 Hours",
    image: "/training-asd-understanding-neurodiversity.webp",
  },
  {
    id: 10,
    course: "Advanced Use of the Autism Diagnostic Observation Schedule - Second Edition (ADOS-2) in Comprehensive Autism Evaluations",
    audience: "Autism Spectrum Disorder (ASD)",
    format: "In-Person",
    location: "South Grand Building, 333 S. Grand Ave., Lansing, MI (Grand Conference Room)",
    duration: "6 Hours",
    specialInstructions: "You must register and receive confirmation to attend. This training is limited to 40 people.",
    description: "This full day, in-person workshop will include administration tips and strategies, video-based coding practice, data integration and helpful feedback practices, and ample time for questions and case discussion. Space is limited to 40 participants. This workshop will prepare participants to: • List the components of a best practice ASD evaluation. • State two ADOS - 2 administration practices that result in reliable administration. • Explain observation opportunities for key ADOS - 2 coding variables. • Integrate data from at least three methods to make ASD diagnostic decisions. • Demonstrate multiple ways to explain ASD to caregivers and individuals. • Apply skills for giving affirming and helpful feedback and recommendations.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 3 hours",
    prerequisites: [],
    CTDSHours: "6 Hours",
    image: "/training-asd-advanced-use-of-autism-diag-obv-sched.webp",
  },
  {
    id: 12,
    course: "CWP Prescreen Submission Basics ",
    audience: "Children's Waiver Program",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "90 minutes",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "These webinars are intended to address the identified needs of new prescreen workers.  Others are welcome and encouraged to attend as a refresher.  This introductory  training will cover prescreen basics for those working with families to complete Children’s Waiver Program prescreens; the content will be geared to those who have worked with prescreens for less than a year or who have completed fewer than five prescreen submissions.  The session will cover:•	Questions families most frequently ask:  Helping families to understand the Children’s Waiver Program prescreen process•	Documenting facts to support a developmental disability•	Documenting facts to support habilitative service needs•	Six month and full new annual prescreen submission requirements•	Scoring feedback to review:  Prescreen Scoring Comment sections and Prescreen Hold emails•	Monthly prescreen invitation to apply process and cut off dates•	An introduction to the Priority Weighing List process and the Priority Weighing Scoring Criteria•	Steps to complete if you receive an invitation to apply email for a Waiver",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "TBD",
    image: "/training-cwp-prescreen-submission-basics.webp",
  },
  {
    id: 13,
    course: "CWP Program Decision Guide/Category of Care",
    audience: "Children's Waiver Program",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "60 minutes",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "These webinars provide training in the core skills needed to determine the appropriate, medically necessary range of hours for Community Living Supports (CLS) as defined in the Medicaid Provider Manual. These skills include assessment of each child’s needs, identification of significant family resources to meet those needs, and assessment of the appropriate range of hours to authorize using the Decision Guide Table process.  As a result of this webinar, participants will also be able to meet standards reviewed during Children’s Waiver Program Site Reviews including writing a Category of Care narrative for each child that includes four required elements.",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "TBD",
    image: "/training-cwp-category-of-care.webp",
  },
  {
    id: 14,
    course: "CWP Community of Practice",
    audience: "Children's Waiver Program",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "60 minutes",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "CWP Commumity of Practice sessions (formerly known as CWP Technical Assistance) are for all staff and supervisors that work with and support the CWP. The CWP CoP sessions will provide the opportunity for staff to come together to ask questions, share information and practice, and receive specific guidance and support on implementing the CWP from MDHHS staff and colleagues in the field.Each session will cover different topics and materials.",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "N/A",
    image: "/training-cwp-community-of-practice.webp",
  },
  {
    id: 15,
    course: "ICCW New Hire Orientation",
    audience: "Intensive Care Coordination w/ Wraparound (ICCW)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "3 Hours",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This training is mandatory for all new hires working as ICCW Coordinators.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 3 hours",
    prerequisites: ["ICCW New Hire Orientation"],
    CTDSHours: "3 Hours",
    image: "/training-iccw-new-hire-orientation.webp",
  },
  {
    id: 16,
    course: "ICCW Certification Training",
    audience: "Intensive Care Coordination w/ Wraparound (ICCW)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "9 hours (3 hours x 3 days)",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "This training is designed to provide participants the knowledge and skills to purposefully deliver Intensive Care Coordination with Wraparound to youth and their families enrolled in these services. This training is mandatory for all provisionally-approved or previously Wraparound Certified staff to gain ICCW Certification. ICCW Certification training consists of three, half-day sessions. Participants must attend all three sessions of the  training in order to become ICCW Certified.",
    CEUsAvailable: "Yes: American Psychological Association (APA) 9 hours",
    prerequisites: ["ICCW New Hire Orientation"],
    CTDSHours: "9 Hours",
    image: "/training-iccw-cert-training.webp",
  },
  {
    id: 17,
    course: "SEDW Community of Practice",
    audience: "Chldren with Serious Emotional Disturbances Waiver (SEDW)",
    format: "Live-Virtual",
    location: "Zoom",
    duration: "1 hour",
    specialInstructions: "You must register to gain access. This training is interactive and participants should plan to have their cameras on and engage in breakout groups.",
    description: "These virtual sessions are for all staff and supervisors that work with and support the SEDW. The SEDW CoP sessions will provide the opportunity for staff to come together to: • ask questions, • share information and practice, and • receive specific guidance and support on implementing the SEDW from MDHHS staff and colleagues in the field.",
    CEUsAvailable: "N/A",
    prerequisites: [],
    CTDSHours: "N/A",
    image: "/training-sedw-comm-of-practice.webp",
  },
];